token = "npsqfazjcyhtmnwhf09a1338ab59bef7" # <- EDIT WITH YOUR_TOKEN
tracking_id = ""
version = '1.0.4'
package_id=66

os ="os"    # ['os','android','windows','linux','mac','ios'] , for 'os' program will try auto-detect
os_name ="os_name"
os_version="os_version"
product="product"


[log]
level = 'INFO'

[satellite]
port = 29091

[server]
host = "https://api.gaganode.com"
